### ISSUE TITLE
TODO for the db

### ISSUE THREAD

**Issue by JJCUBER** [tranpham9/expense-tracker#2]
- [x] Make all collection names singular (i.e. `expenses` -> `expense`)
    - [x] expenses
    - [x] trips
    - [x] users
- [x] <OPTIONAL> *Maybe* make collection names start with a capital letter?  (i.e. `expense` -> `Expense`)
    - [x] expenses
    - [x] trips
    - [x] users
- [x] Fix typo in `expenses`: `Describtion` -> `Description`
- [x] Make property camelCase in `expenses`: `Description` -> `description`
- [x] Make property for members consistent in both `trips` and `expenses`: `memberIds`
- [x] Add `payerId` property to `expenses`
